# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(blank=True, max_length=30, null=True, verbose_name='Norma')),
                ('pcosto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Precio de Costo')),
                ('pventa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Precio de Venta')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('mprima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MateriaPrima', to='materiaprima.mprima')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='Producto', upload_to='producto/', verbose_name='imagen')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Producto')),
                ('pcosto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Precio de Costo')),
                ('pventa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Precio de Venta')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Registro')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('observacion', models.TextField(blank=True, max_length=30, null=True, verbose_name='Observacion')),
                ('activo', models.BooleanField(max_length=256, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.tipo'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='producto.producto'),
        ),
    ]
