# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='producto/', verbose_name='imagen'),
        ),
    ]
