# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cantidad')),
                ('importe', models.CharField(blank=True, max_length=30, null=True, verbose_name='Importe')),
                ('pcosto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Precio de Costo')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo')),
            ],
        ),
    ]
