# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='movimiento.tipo'),
        ),
    ]
