# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('movimiento', '0002_auto_20171111_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cliente',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
