# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0003_movimiento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='confirmado',
            field=models.BooleanField(default=0, max_length=256, verbose_name='Confirmado'),
            preserve_default=False,
        ),
    ]
