# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nom_Cargo_Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Funciones')),
                ('resposabilidad', models.TextField(blank=True, max_length=256, null=True, verbose_name='Responsabilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Habilidad_Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(blank=True, max_length=256, null=True, verbose_name='Habilidad')),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Titulo_Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Categoria Profecional')),
                ('especialidad', models.TextField(blank=True, max_length=256, null=True, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, null=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, default='Empleado', upload_to='empleado/', verbose_name='imagen')),
                ('carne', models.CharField(blank=True, max_length=256, null=True, verbose_name='Carne de Identidad')),
                ('correo', models.EmailField(max_length=256, null=True, verbose_name='Correo electronico')),
                ('direccion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Direccion')),
                ('graduado', models.CharField(blank=True, max_length=256, null=True, verbose_name='Graduado de ')),
                ('telefono', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telefono')),
                ('registro', models.DateTimeField(auto_now=True, verbose_name='Registrado')),
                ('estado', models.BooleanField(max_length=256, verbose_name='Estado')),
                ('cargo', models.ManyToManyField(blank=True, null=True, to='empleado.Nom_Cargo_Trabajador')),
                ('titulo', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.Nom_Titulo_Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=250)),
                ('unidad', models.CharField(blank=True, max_length=250)),
                ('departamento', models.CharField(blank=True, max_length=250)),
                ('trabajador', models.CharField(blank=True, max_length=250)),
                ('accion', models.CharField(blank=True, max_length=250)),
                ('numaccion', models.IntegerField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=250)),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Registrado el: ')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabajador',
            field=models.ForeignKey(blank=True, max_length=256, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='empleado.Trabajador'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
