# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.ManyToManyField(blank=True, to='empleado.Nom_Cargo_Trabajador'),
        ),
    ]
